/* @flow */

export default (moduleName: string, version: string) => `/* @flow */
/**
 * Flowtype definitions for ${moduleName}
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v${version}
 * Repo: https://github.com/scaphold-io/flowgen
 */

`;
